### ISSUE TITLE
captions: loadCaptions undefined (regression)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/flowplayer-core#574]
```
What steps will reproduce the problem?
1. demo with comparison: 
http://flowplayer.blacktrash.org/test/captionswitch.html

What is the expected output? What do you see instead?
Expected: loadCaptions should work with flowplayer 3.2.11 and captions 3.2.8
Instead: loadCaptions is undefined:
TypeError: 'undefined' is not a function (evaluating 
'player2.getPlugin("captions").loadCaptions(0, currentcaption2)')

```

Original issue reported on code.google.com by `blacktrashproduct` on 25 May 2012 at 12:51
